server:
  port: 8080
  context-path: /one

projectConfig:
  one: name_dev
  two: age_dev

spring:
  datasource:
    password: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    #INIT=RUNSCRIPT FROM './src/main/resources/init_table.sql'

