server:
  port: 8080
  context-path: /one

projectConfig:
  one: name_dev
  two: age_dev

spring:
  datasource:
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/github/springbootLearning/one/duke
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #INIT=RUNSCRIPT FROM './src/main/resources/init_table.sql'

