server:
  port: 8080
  context-path: /sell

projectConfig:
  one: name_dev
  two: age_dev

#spring:
#  datasource:
#    password:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/github/springbootLearning/one/duke
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#INIT=RUNSCRIPT FROM './src/main/resources/init_table.sql'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.107.52/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false

